<script setup lang="ts">
import type { Finding } from '../types/analysis'
import { confidencePercent } from '../services/recommendationUx'
import EvidenceList from './EvidenceList.vue'
import StatusBadge from './StatusBadge.vue'
defineProps<{ finding: Finding }>()
</script>
<template><article class="finding-card"><header><div><p class="category">{{ finding.category }}</p><h3>{{ finding.title }}</h3></div><StatusBadge :status="finding.severity" /></header><p class="short-summary">{{ finding.summary }}</p><div class="quick-meta"><span>Confidence {{ confidencePercent(finding.confidence) }}</span><span>{{ finding.evidenceRefs.length }} evidence refs</span></div><details class="finding-details"><summary>View Details</summary><div class="detail-body"><p>{{ finding.summary }}</p><section><h4>Scope</h4><div class="chips"><span v-for="value in finding.scope" :key="value">{{ value }}</span><span v-if="!finding.scope.length">—</span></div></section><EvidenceList :evidence="finding.evidenceRefs" /></div></details></article></template>
<style scoped>.finding-card{display:grid;gap:.7rem;padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-small)}header{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}h3,h4,p{margin:0}.category{margin-bottom:.3rem;color:var(--color-primary-strong);font-size:.72rem;font-weight:700;text-transform:uppercase}.short-summary{display:-webkit-box;overflow:hidden;color:var(--color-text);line-height:1.55;-webkit-box-orient:vertical;-webkit-line-clamp:2}.quick-meta{display:flex;flex-wrap:wrap;gap:.75rem;color:var(--color-text-muted);font-size:.8rem}.finding-details>summary{cursor:pointer;color:var(--color-primary-strong);font-weight:700}.detail-body{display:grid;gap:.8rem;margin-top:.8rem}.chips{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.4rem}.chips span{padding:.25rem .5rem;border-radius:999px;background:rgb(255 255 255 / 5%);color:var(--color-text-muted)}@media(max-width:560px){header{flex-direction:column}}</style>
