<script setup lang="ts">
import { computed } from 'vue'
import { canCreateRecommendationWorkItem, canDeferRecommendation, canIgnoreRecommendation, canViewRecommendation, confidencePercent, requiresApprovalWarning } from '../services/recommendationUx'
import type { RecommendationView } from '../types/analysis'
import type { BacklogItem } from '../types/backlog'
import EvidenceList from './EvidenceList.vue'
import StatusBadge from './StatusBadge.vue'

const props = defineProps<{ item: RecommendationView; workItem?: BacklogItem; busy?: boolean }>()
const emit = defineEmits<{ view: [id: string]; defer: [id: string]; ignore: [id: string]; createWorkItem: [item: RecommendationView] }>()
const next = computed(() => props.item.recommendedNextAction)
</script>
<template><article class="recommendation-card" :class="`is-${item.status.toLowerCase()}`">
  <header class="card-header"><div><p class="eyebrow">Recommendation</p><h3>{{ item.title }}</h3></div><StatusBadge :status="item.status" /></header>
  <div class="decision-strip"><span><b>Priority</b> <StatusBadge :status="item.priority" size="small" /></span><span><b>Risk</b> <StatusBadge :status="item.risk" size="small" /></span><span><b>Benefit</b> {{ item.benefit }}</span><span><b>Confidence</b> {{ confidencePercent(item.confidence) }}</span><span><b>Mode</b> <StatusBadge :status="item.suggestedExecutionMode" size="small" /></span></div>
  <p class="short-rationale">{{ item.rationale }}</p>
  <el-alert v-if="requiresApprovalWarning(item)" class="approval-warning" type="warning" :closable="false" show-icon title="READ_WRITE · Approval Required"><p>Recommendation suggests READ_WRITE, but it grants no execution authority. Approval remains required before execution.</p></el-alert>
  <section class="next-action-summary"><div><p class="eyebrow">Recommended Next Action</p><h4>{{ next.title }}</h4></div><StatusBadge :status="next.estimatedComplexity" size="small" /><p>{{ next.description }}</p></section>
  <div v-if="item.status === 'DEFERRED'" class="decision-note"><strong>Deferred</strong><span v-if="item.deferUntil">Until {{ item.deferUntil }}</span><span v-if="item.deferReason">{{ item.deferReason }}</span></div>
  <div v-else-if="item.status === 'IGNORED'" class="decision-note is-ignored"><strong>Ignored</strong><span v-if="item.ignoreReason">{{ item.ignoreReason }}</span></div>
  <div v-else-if="item.status === 'WORKITEM_CREATED'" class="work-item-result"><div><strong>WorkItem Created</strong><p>{{ workItem?.title || item.convertedBacklogItemId }} · {{ workItem?.status || 'IDEA' }}</p><small>Backlog ID: {{ item.convertedBacklogItemId }}</small></div><RouterLink v-if="item.convertedBacklogItemId" :to="`/backlog?item=${encodeURIComponent(item.convertedBacklogItemId)}`">Open in Backlog →</RouterLink></div>
  <details class="recommendation-details"><summary>View Details</summary><div class="detail-body"><section><h4>Recommendation Details</h4><p>{{ item.rationale }}</p><dl><div><dt>Priority</dt><dd>{{ item.priority }}</dd></div><div><dt>Risk</dt><dd>{{ item.risk }}</dd></div><div><dt>Benefit</dt><dd>{{ item.benefit }}</dd></div><div><dt>Confidence</dt><dd>{{ confidencePercent(item.confidence) }}</dd></div></dl><h5>Scope</h5><p>{{ item.scope.join(', ') || '—' }}</p><h5>Dependencies</h5><p>{{ item.dependencies.join(', ') || '—' }}</p></section><section class="next-action-detail"><p class="eyebrow">Recommended Next Action</p><h4>{{ next.title }}</h4><p>{{ next.description }}</p><p><strong>Goal:</strong> {{ next.goal }}</p><dl><div><dt>Complexity</dt><dd>{{ next.estimatedComplexity }}</dd></div><div><dt>Execution Mode</dt><dd>{{ next.suggestedExecutionMode }}</dd></div><div><dt>Approval</dt><dd>{{ next.approvalRequired ? 'Required' : 'Not requested' }}</dd></div></dl><h5>Acceptance Criteria</h5><ul><li v-for="criterion in next.acceptanceCriteria" :key="criterion">{{ criterion }}</li></ul><h5>Scope</h5><p>{{ next.scope.join(', ') || '—' }}</p><h5>Dependencies</h5><p>{{ next.dependencies.join(', ') || '—' }}</p></section><details v-if="item.findings.length" class="linked-findings"><summary>Linked Findings ({{ item.findings.length }})</summary><ul><li v-for="finding in item.findings" :key="finding.findingId"><strong>{{ finding.title }}</strong> · {{ finding.severity }}</li></ul></details><EvidenceList :evidence="item.evidenceRefs" /></div></details>
  <footer class="actions"><el-button v-if="canCreateRecommendationWorkItem(item.status)" type="primary" :loading="busy" @click="emit('createWorkItem', item)">Create WorkItem</el-button><el-button v-if="canViewRecommendation(item.status)" :loading="busy" @click="emit('view', item.recommendationId)">{{ item.status === 'DEFERRED' ? 'View / Reactivate' : 'Mark as Viewed' }}</el-button><el-button v-if="canDeferRecommendation(item.status)" :loading="busy" @click="emit('defer', item.recommendationId)">Defer</el-button><el-button v-if="canIgnoreRecommendation(item.status)" plain type="danger" :loading="busy" @click="emit('ignore', item.recommendationId)">Ignore</el-button></footer>
</article></template>
<style scoped>.recommendation-card{display:grid;gap:.85rem;padding:1rem;border:1px solid var(--color-border);border-left:4px solid var(--color-primary);border-radius:var(--radius-small)}.recommendation-card.is-ignored{opacity:.78;border-left-color:var(--color-text-muted)}.recommendation-card.is-workitem_created{border-left-color:var(--color-success)}.card-header,.actions,.work-item-result{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}h3,h4,h5,p{margin:0}.eyebrow{margin:0 0 .3rem;color:var(--color-primary-strong);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.decision-strip{display:flex;flex-wrap:wrap;gap:.55rem 1rem;color:var(--color-text-muted);font-size:.8rem}.decision-strip span{display:flex;align-items:center;gap:.35rem}.short-rationale,.next-action-summary>p{display:-webkit-box;overflow:hidden;line-height:1.55;-webkit-box-orient:vertical;-webkit-line-clamp:2}.next-action-summary{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.4rem 1rem;padding:.85rem;border-left:3px solid var(--color-primary);background:rgb(255 255 255 / 3%)}.next-action-summary>p{grid-column:1/-1;color:var(--color-text-muted)}.decision-note{display:flex;flex-wrap:wrap;gap:.5rem 1rem;padding:.65rem;color:var(--color-warning);background:rgb(230 162 60 / 8%)}.decision-note.is-ignored{color:var(--color-text-muted)}.work-item-result{align-items:center;padding:.8rem;border-left:3px solid var(--color-success);background:rgb(103 194 58 / 8%)}.work-item-result small{color:var(--color-text-muted)}.work-item-result a{color:var(--color-primary-strong);font-weight:700;text-decoration:none}.recommendation-details>summary,.linked-findings>summary{cursor:pointer;color:var(--color-primary-strong);font-weight:700}.detail-body{display:grid;gap:1rem;margin-top:.8rem}.detail-body>section{display:grid;gap:.6rem;padding:.85rem;border:1px solid var(--color-border);border-radius:var(--radius-small)}dl{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem;margin:0}dt{color:var(--color-text-muted);font-size:.72rem;text-transform:uppercase}dd{margin:.2rem 0 0}.linked-findings{padding:.65rem;border:1px solid var(--color-border);border-radius:var(--radius-small)}.actions{justify-content:flex-end;flex-wrap:wrap;padding-top:.25rem}@media(max-width:680px){.card-header,.work-item-result{flex-direction:column}.next-action-summary,dl{grid-template-columns:1fr}.actions{justify-content:flex-start}.actions :deep(.el-button){margin-left:0}}
</style>
