package com.aidevos.orchestrator.qualitygate;

import java.time.Instant; import java.util.List; import java.util.Map; import java.util.Optional;
import com.aidevos.orchestrator.audit.AuditService; import com.aidevos.orchestrator.human.*; import com.aidevos.orchestrator.taskcenter.*; import com.aidevos.orchestrator.validation.*; import com.aidevos.orchestrator.validation.security.*; import org.junit.jupiter.api.Test; import tools.jackson.databind.ObjectMapper;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;

class QualityGateServiceTest {
	@Test void requiredFailureBlocks(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");r.getChecks().add(check(true,ValidationStatus.FAILED));f.runs.save(r);assertEquals(QualityGateDecision.BLOCK,f.service.evaluate("r1").getDecision());}
	@Test void secretAndCriticalBlock(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");f.runs.save(r);f.reports.save(report("r1",finding(SecurityCategory.SECRET,SecuritySeverity.HIGH)));assertEquals(QualityGateDecision.BLOCK,f.service.evaluate("r1").getDecision());ValidationRun r2=run("r2");f.runs.save(r2);f.reports.save(report("r2",finding(SecurityCategory.DEPENDENCY,SecuritySeverity.CRITICAL)));assertEquals(QualityGateDecision.BLOCK,f.service.evaluate("r2").getDecision());}
	@Test void highRequiresOneIdempotentApprovalAndApprovePasses(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");f.runs.save(r);f.reports.save(report("r1",finding(SecurityCategory.SAST,SecuritySeverity.HIGH)));QualityGateResult first=f.service.evaluate("r1"),second=f.service.evaluate("r1");assertSame(first,second);assertEquals(QualityGateDecision.REQUIRE_APPROVAL,first.getDecision());assertEquals(1,f.approvals.listByTask("task-1").size());QualityGateResult approved=f.service.approve(first.getGateResultId(),"reviewer","accepted");assertEquals(QualityGateDecision.PASS,approved.getDecision());assertSame(approved,f.service.approve(first.getGateResultId(),"reviewer","again"));assertDoesNotThrow(()->f.service.assertAllowed("task-1"));}
	@Test void rejectBlocksIdempotently(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");f.runs.save(r);f.reports.save(report("r1",finding(SecurityCategory.SAST,SecuritySeverity.HIGH)));QualityGateResult g=f.service.evaluate("r1");assertEquals(QualityGateDecision.BLOCK,f.service.reject(g.getGateResultId(),"reviewer","no").getDecision());assertSame(g,f.service.reject(g.getGateResultId(),"reviewer","again"));assertThrows(IllegalStateException.class,()->f.service.assertAllowed("task-1"));}
	@Test void mediumLowAndCleanPassWithWarningOnly(){for(SecuritySeverity severity:List.of(SecuritySeverity.MEDIUM,SecuritySeverity.LOW)){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r"+severity);f.runs.save(r);f.reports.save(report(r.getValidationRunId(),finding(SecurityCategory.SAST,severity)));assertEquals(QualityGateDecision.PASS,f.service.evaluate(r.getValidationRunId()).getDecision());}}
	@Test void unavailableRequiresReview(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");ValidationCheck c=new ValidationCheck("security",ValidationCheckType.SECURITY,"Security / Trivy",false,false);c.setStatus(ValidationStatus.SKIPPED);c.setMetadata(Map.of("availability","UNAVAILABLE"));r.getChecks().add(c);f.runs.save(r);assertEquals(QualityGateDecision.REQUIRE_APPROVAL,f.service.evaluate("r1").getDecision());}
	@Test void scannerExecutionErrorBlocksInsteadOfPassingAsZeroFindings(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun r=run("r1");ValidationCheck c=new ValidationCheck("security",ValidationCheckType.SECURITY,"Security / Trivy",false,false);c.setStatus(ValidationStatus.FAILED);r.getChecks().add(c);f.runs.save(r);assertEquals(QualityGateDecision.BLOCK,f.service.evaluate("r1").getDecision());}
	@Test void latestRunInvalidatesOldGateAndReadOnlyNeverWrites(){Fixture f=fixture(ExecutionMode.READ_WRITE);ValidationRun old=run("old");old.setStartedAt(Instant.parse("2026-01-01T00:00:00Z"));f.runs.save(old);f.service.evaluate("old");assertDoesNotThrow(()->f.service.assertAllowed("task-1"));ValidationRun newer=run("new");newer.setStartedAt(Instant.parse("2026-01-02T00:00:00Z"));f.runs.save(newer);assertThrows(IllegalStateException.class,()->f.service.assertAllowed("task-1"));Fixture ro=fixture(ExecutionMode.READ_ONLY);ValidationRun rr=run("ro");ro.runs.save(rr);ro.service.evaluate("ro");assertThrows(IllegalStateException.class,()->ro.service.assertAllowed("task-1"));}
	@Test void noValidationOrGateIsDenied(){Fixture f=fixture(ExecutionMode.READ_WRITE);assertThrows(IllegalStateException.class,()->f.service.assertAllowed("task-1"));ValidationRun r=run("r1");f.runs.save(r);assertThrows(IllegalStateException.class,()->f.service.assertAllowed("task-1"));}
	private Fixture fixture(ExecutionMode mode){InMemoryQualityGateRepository gates=new InMemoryQualityGateRepository();InMemoryValidationRepository runs=new InMemoryValidationRepository();InMemorySecurityReportRepository reports=new InMemorySecurityReportRepository();InMemoryHumanApprovalRepository approvals=new InMemoryHumanApprovalRepository();TaskCenterService tasks=mock(TaskCenterService.class);when(tasks.getTask("task-1")).thenReturn(Optional.of(new TaskRecord("task-1","t","d","project-1","workspace-1",mode)));QualityGateService service=new QualityGateService(gates,runs,reports,new QualityGatePolicy(),approvals,tasks,AuditService.noop(),new ObjectMapper());return new Fixture(service,runs,reports,approvals);}
	private ValidationRun run(String id){ValidationRun r=new ValidationRun(id,"task-1","project-1","workspace-1",null,null);r.setStatus(ValidationStatus.SUCCESS);r.setStartedAt(Instant.now());r.setCompletedAt(Instant.now());return r;}
	private ValidationCheck check(boolean required,ValidationStatus status){ValidationCheck c=new ValidationCheck("check",ValidationCheckType.BACKEND_TEST,"Backend Test",required,required);c.setStatus(status);return c;}
	private SecurityReport report(String run,SecurityFinding finding){SecurityReport r=new SecurityReport();r.setReportId("report-"+run);r.setValidationRunId(run);r.setTaskId("task-1");r.setProjectId("project-1");r.setWorkspaceId("workspace-1");r.setScanner(SecurityScannerType.SEMGREP);r.setStatus(SecurityScanStatus.FINDINGS_DETECTED);r.setFindings(List.of(finding));return r;}
	private SecurityFinding finding(SecurityCategory category,SecuritySeverity severity){SecurityFinding f=new SecurityFinding();f.setFindingId("finding-"+category+severity);f.setCategory(category);f.setSeverity(severity);f.setScanner(SecurityScannerType.SEMGREP);f.setTitle(category+" finding");f.setFingerprint("fp");return f;}
	private record Fixture(QualityGateService service,InMemoryValidationRepository runs,InMemorySecurityReportRepository reports,InMemoryHumanApprovalRepository approvals){}
}
