package com.aidevos.orchestrator.network;
import com.aidevos.orchestrator.audit.AuditService;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
class NetworkSettingsServiceTest {
	@Test void credentialsAreRedactedAndMaskedUpdatePreservesSecret(){InMemoryNetworkSettingsRepository repo=new InMemoryNetworkSettingsRepository();WindowsHostResolver resolver=mock(WindowsHostResolver.class);ProxyEnvironmentService env=new ProxyEnvironmentService(repo,resolver);NetworkSettingsService service=new NetworkSettingsService(env,resolver,AuditService.noop());ProxySettings settings=new ProxySettings();settings.setMode(ProxyMode.CUSTOM);settings.setHostStrategy(ProxyHostStrategy.MANUAL);settings.setHttpProxy("http://alice:secret@proxy.local:8080");ProxySettingsView first=service.save(settings);assertFalse(first.httpProxy().contains("secret"));assertTrue(first.httpProxy().contains(NetworkSettingsService.MASK));ProxySettings update=new ProxySettings();update.setMode(ProxyMode.CUSTOM);update.setHostStrategy(ProxyHostStrategy.MANUAL);update.setHttpProxy(first.httpProxy());service.save(update);assertEquals("http://alice:secret@proxy.local:8080",repo.get().getHttpProxy());}
	@Test void localTargetsAreAlwaysDirectAndNewVersionGetsNewClient(){InMemoryNetworkSettingsRepository repo=new InMemoryNetworkSettingsRepository();ProxyEnvironmentService env=new ProxyEnvironmentService(repo,mock(WindowsHostResolver.class));NetworkAwareHttpClientFactory factory=new NetworkAwareHttpClientFactory(env);ProxySettings s=new ProxySettings();s.setMode(ProxyMode.CUSTOM);s.setHostStrategy(ProxyHostStrategy.MANUAL);s.setHttpProxy("http://proxy.local:8080");env.save(s);var first=factory.client(java.time.Duration.ofSeconds(1));assertEquals(NetworkRoute.DIRECT,factory.route(java.net.URI.create("http://127.0.0.1:18789")));assertEquals(NetworkRoute.PROXY,factory.route(java.net.URI.create("https://github.com")));env.save(s);assertNotSame(first,factory.client(java.time.Duration.ofSeconds(1)));}
}
