package com.aidevos.orchestrator.validation.security;

import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.ArrayList; import java.util.HexFormat; import java.util.List; import java.util.UUID;
import org.springframework.stereotype.Component; import tools.jackson.databind.JsonNode; import tools.jackson.databind.ObjectMapper;
@Component public class SecurityFindingParser {
	private final ObjectMapper mapper; private final SecurityRedactor redactor; public SecurityFindingParser(ObjectMapper m,SecurityRedactor r){mapper=m;redactor=r;}
	public List<SecurityFinding> parse(SecurityScannerType scanner,String json){try{JsonNode root=mapper.readTree(json==null||json.isBlank()?"[]":json);return switch(scanner){case GITLEAKS->gitleaks(root);case SEMGREP->semgrep(root);case TRIVY->trivy(root);};}catch(Exception e){throw new IllegalArgumentException("Malformed "+scanner+" result",e);}}
	private List<SecurityFinding> gitleaks(JsonNode root){List<SecurityFinding> out=new ArrayList<>();for(JsonNode n:root){out.add(finding(SecurityScannerType.GITLEAKS,SecurityCategory.SECRET,SecuritySeverity.HIGH,text(n,"RuleID"),text(n,"Description"),"Potential secret detected",text(n,"File"),integer(n,"StartLine"),null,null,null));}return out;}
	private List<SecurityFinding> semgrep(JsonNode root){List<SecurityFinding> out=new ArrayList<>();for(JsonNode n:root.path("results")){JsonNode extra=n.path("extra");out.add(finding(SecurityScannerType.SEMGREP,SecurityCategory.SAST,severity(text(extra,"severity")),text(n,"check_id"),text(extra,"message"),text(extra,"message"),text(n,"path"),n.path("start").path("line").asInt(0),null,null,null));}return out;}
	private List<SecurityFinding> trivy(JsonNode root){List<SecurityFinding> out=new ArrayList<>();for(JsonNode result:root.path("Results")){String target=text(result,"Target");for(JsonNode n:result.path("Vulnerabilities"))out.add(finding(SecurityScannerType.TRIVY,SecurityCategory.DEPENDENCY,severity(text(n,"Severity")),text(n,"VulnerabilityID"),text(n,"Title"),text(n,"Description"),target,null,text(n,"PkgName"),text(n,"InstalledVersion"),text(n,"FixedVersion")));for(JsonNode n:result.path("Misconfigurations"))out.add(finding(SecurityScannerType.TRIVY,SecurityCategory.CONFIGURATION,severity(text(n,"Severity")),text(n,"ID"),text(n,"Title"),text(n,"Message"),target,n.path("CauseMetadata").path("StartLine").asInt(0),null,null,null));}return out;}
	private SecurityFinding finding(SecurityScannerType scanner,SecurityCategory category,SecuritySeverity severity,String rule,String title,String message,String file,Integer line,String pkg,String installed,String fixed){SecurityFinding f=new SecurityFinding();f.setFindingId("finding-"+UUID.randomUUID());f.setScanner(scanner);f.setCategory(category);f.setSeverity(severity);f.setRuleId(blank(rule,"unknown"));f.setTitle(redactor.redact(blank(title,rule)));f.setMessage(redactor.redact(blank(message,title)));f.setFile(file);f.setLine(line==null||line==0?null:line);f.setPackageName(pkg);f.setInstalledVersion(installed);f.setFixedVersion(fixed);if(category==SecurityCategory.DEPENDENCY)f.setVulnerabilityId(rule);f.setRecommendation(fixed==null||fixed.isBlank()?"Review and remediate this finding":"Upgrade to "+fixed);f.setBlockingCandidate(category==SecurityCategory.SECRET||severity==SecuritySeverity.CRITICAL||severity==SecuritySeverity.HIGH);f.setFingerprint(hash(scanner+"|"+rule+"|"+file+"|"+line+"|"+pkg));return f;}
	private String text(JsonNode n,String key){JsonNode v=n.path(key);return v.isMissingNode()||v.isNull()?null:v.asText();}private Integer integer(JsonNode n,String key){int v=n.path(key).asInt(0);return v==0?null:v;}
	private SecuritySeverity severity(String v){if(v==null)return SecuritySeverity.INFO;try{return SecuritySeverity.valueOf(v.toUpperCase());}catch(Exception e){return "WARNING".equalsIgnoreCase(v)?SecuritySeverity.MEDIUM:SecuritySeverity.INFO;}}
	private String blank(String a,String b){return a==null||a.isBlank()?b:a;} private String hash(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
