package com.aidevos.orchestrator.validation.security;

import java.time.Duration; import java.time.Instant; import java.util.ArrayList; import java.util.EnumMap; import java.util.LinkedHashMap; import java.util.List; import java.util.Map; import java.util.UUID;
import com.aidevos.orchestrator.audit.*; import com.aidevos.orchestrator.executor.command.*; import com.aidevos.orchestrator.validation.*; import com.aidevos.orchestrator.validation.provider.*; import org.springframework.stereotype.Service; import tools.jackson.databind.ObjectMapper;
@Service public class SecurityValidationService {
	private final CommandExecutor executor; private final SecurityScannerAvailability availability; private final SecurityFindingParser parser; private final SecurityRedactor redactor; private final SecurityReportRepository reports; private final ValidationEvidenceService evidence; private final AuditService audit; private final ObjectMapper mapper;
	public SecurityValidationService(CommandExecutor e,SecurityScannerAvailability a,SecurityFindingParser p,SecurityRedactor r,SecurityReportRepository repo,ValidationEvidenceService ev,AuditService au,ObjectMapper m){executor=e;availability=a;parser=p;redactor=r;reports=repo;evidence=ev;audit=au;mapper=m;}
	public ValidationCheckResult execute(ValidationContext context,SecurityScannerType scanner){Instant started=Instant.now();String reportId="security-report-"+UUID.randomUUID();ScannerAvailability av=availability.detect(scanner);audit.validationEvent(EventType.SECURITY_SCANNER_STARTED,context.taskId(),context.validationRunId(),null,"RUNNING",scanner+" scanner started",Map.of("scanner",scanner.name()));
		if(av.status()!=ScannerAvailabilityStatus.AVAILABLE){SecurityReport report=report(context,scanner,reportId,started,List.of(),SecurityScanStatus.NOT_AVAILABLE);report.setSummary(scanner+" not available");reports.save(report);return new ValidationCheckResult(ValidationStatus.SKIPPED,scanner+" NOT AVAILABLE",av.message(),null,null,List.of(),metadata(report,av,List.of()));}
		CommandOptions options=new CommandOptions();options.setWorkingDirectory(context.workspacePath().toString());options.setTimeout(Duration.ofMinutes(15));options.setCommand(command(scanner));CommandResult result=executor.execute(options);String raw=redactor.redact((result.getOutput()==null?"":result.getOutput())+(result.getError()==null?"":"\n"+result.getError()));
		if(!result.isSuccess()){SecurityReport report=report(context,scanner,reportId,started,List.of(),SecurityScanStatus.SCAN_ERROR);report.setSummary("Scanner execution failed");String log=evidence.saveContent(context.validationRunId(),"security-"+scanner,context.taskId(),scanner.name().toLowerCase()+"-execution.log","text/plain",raw,artifactMetadata(report));report.setArtifactIds(List.of(log));reports.save(report);audit.validationEvent(EventType.SECURITY_SCANNER_FAILED,context.taskId(),context.validationRunId(),"RUNNING","FAILED",scanner+" scanner failed",Map.of("scanner",scanner.name()));return new ValidationCheckResult(ValidationStatus.FAILED,"Scanner execution failed",useful(result),null,null,List.of(),metadata(report,av,List.of(log)));}
		try{List<SecurityFinding> findings=parser.parse(scanner,result.getOutput());SecurityReport report=report(context,scanner,reportId,started,findings,findings.isEmpty()?SecurityScanStatus.SUCCESS:SecurityScanStatus.FINDINGS_DETECTED);report.setSummary(findings.size()+" security findings");long high=findings.stream().filter(f->f.getSeverity()==SecuritySeverity.HIGH).count();long critical=findings.stream().filter(f->f.getSeverity()==SecuritySeverity.CRITICAL).count();if(high+critical>0)audit.validationEvent(EventType.SECURITY_FINDING_DETECTED,context.taskId(),context.validationRunId(),null,report.getStatus().name(),"High-severity security findings detected",Map.of("scanner",scanner.name(),"high",high,"critical",critical));String rawId=evidence.saveContent(context.validationRunId(),"security-"+scanner,context.taskId(),scanner.name().toLowerCase()+"-sanitized-raw.json","application/json",raw,artifactMetadata(report));String normalized=redactor.redact(mapper.writeValueAsString(report));String normalizedId=evidence.saveContent(context.validationRunId(),"security-"+scanner,context.taskId(),scanner.name().toLowerCase()+"-security-report.json","application/json",normalized,artifactMetadata(report));report.setArtifactIds(List.of(normalizedId,rawId));reports.save(report);audit.validationEvent(EventType.SECURITY_REPORT_CREATED,context.taskId(),context.validationRunId(),null,report.getStatus().name(),scanner+" security report created",Map.of("scanner",scanner.name(),"findings",findings.size()));audit.validationEvent(EventType.SECURITY_SCANNER_COMPLETED,context.taskId(),context.validationRunId(),"RUNNING","SUCCESS",scanner+" scanner completed",Map.of("scanner",scanner.name(),"findings",findings.size()));return new ValidationCheckResult(ValidationStatus.SUCCESS,report.getSummary(),null,null,null,List.of(),metadata(report,av,report.getArtifactIds()));}catch(Exception ex){SecurityReport report=report(context,scanner,reportId,started,List.of(),SecurityScanStatus.SCAN_ERROR);report.setSummary("Invalid scanner result");reports.save(report);audit.validationEvent(EventType.SECURITY_SCANNER_FAILED,context.taskId(),context.validationRunId(),"RUNNING","FAILED",scanner+" scanner returned invalid output",Map.of("scanner",scanner.name()));return new ValidationCheckResult(ValidationStatus.FAILED,"Invalid scanner result",ex.getMessage(),null,null,List.of(),metadata(report,av,List.of()));}}
	public List<SecurityReport> byRun(String id){return reports.findByValidationRunId(id);} public SecurityReport get(String id){SecurityReport r=reports.get(id);if(r==null)throw new com.aidevos.orchestrator.common.exception.ResourceNotFoundException("SecurityReport",id);return r;}
	private List<String> command(SecurityScannerType s){return switch(s){case GITLEAKS->List.of("gitleaks","detect","--source",".","--report-format","json","--report-path","/dev/stdout","--exit-code","0","--no-banner");case SEMGREP->List.of("semgrep","scan","--config","p/security-audit","--json","--metrics","off",".");case TRIVY->List.of("trivy","fs","--format","json","--scanners","vuln,misconfig,secret","--exit-code","0",".");};}
	private SecurityReport report(ValidationContext c,SecurityScannerType s,String id,Instant start,List<SecurityFinding> f,SecurityScanStatus status){SecurityReport r=new SecurityReport();r.setReportId(id);r.setTaskId(c.taskId());r.setProjectId(c.projectId());r.setWorkspaceId(c.workspaceId());r.setValidationRunId(c.validationRunId());r.setScanner(s);r.setStatus(status);r.setFindings(f);EnumMap<SecuritySeverity,Integer> counts=new EnumMap<>(SecuritySeverity.class);for(SecuritySeverity sev:SecuritySeverity.values())counts.put(sev,0);for(SecurityFinding x:f)counts.merge(x.getSeverity(),1,Integer::sum);r.setCountsBySeverity(counts);r.setStartedAt(start);r.setCompletedAt(Instant.now());r.setDurationMs(Duration.between(start,r.getCompletedAt()).toMillis());return r;}
	private Map<String,Object> metadata(SecurityReport r,ScannerAvailability a,List<String> artifacts){Map<String,Object> m=new LinkedHashMap<>();m.put("scanner",r.getScanner().name());m.put("availability",a.status().name());m.put("securityReportId",r.getReportId());m.put("totalFindings",r.getFindings().size());for(SecuritySeverity s:SecuritySeverity.values())m.put(s.name().toLowerCase(),r.getCountsBySeverity().getOrDefault(s,0));m.put("artifactIds",artifacts);return m;}
	private Map<String,Object> artifactMetadata(SecurityReport r){return Map.of("taskId",r.getTaskId(),"validationRunId",r.getValidationRunId(),"securityReportId",r.getReportId(),"scanner",r.getScanner().name());}
	private String useful(CommandResult r){String v=r.getError();if(v==null||v.isBlank())v=r.getOutput();return redactor.redact(v==null?"Scanner failed":v).strip();}
}
