package com.aidevos.orchestrator.qualitygate;

import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.time.Instant; import java.util.ArrayList; import java.util.Comparator; import java.util.EnumMap; import java.util.HexFormat; import java.util.LinkedHashMap; import java.util.List; import java.util.Map; import java.util.UUID;
import com.aidevos.orchestrator.audit.AuditService; import com.aidevos.orchestrator.audit.EventType; import com.aidevos.orchestrator.common.exception.ResourceNotFoundException; import com.aidevos.orchestrator.human.*; import com.aidevos.orchestrator.taskcenter.*; import com.aidevos.orchestrator.validation.*; import com.aidevos.orchestrator.validation.security.*; import com.aidevos.orchestrator.execution.workspace.ExecutionWorkspacePromotionService; import org.springframework.stereotype.Service; import tools.jackson.databind.ObjectMapper;

@Service public class QualityGateService {
	private final QualityGateRepository gates; private final ValidationRepository validations; private final SecurityReportRepository reports; private final QualityGatePolicy policy; private final HumanApprovalRepository approvals; private final TaskCenterService tasks; private final AuditService audit; private final ObjectMapper mapper; private volatile ExecutionWorkspacePromotionService executionWorkspaces;
	public QualityGateService(QualityGateRepository g,ValidationRepository v,SecurityReportRepository r,QualityGatePolicy p,HumanApprovalRepository a,TaskCenterService t,AuditService au,ObjectMapper m){gates=g;validations=v;reports=r;policy=p;approvals=a;tasks=t;audit=au;mapper=m;}
	@org.springframework.beans.factory.annotation.Autowired(required=false) public void setExecutionWorkspaces(ExecutionWorkspacePromotionService value){executionWorkspaces=value;}
	public synchronized QualityGateResult evaluate(String runId){ValidationRun run=validations.get(runId);if(run==null)throw new ResourceNotFoundException("ValidationRun",runId);requireOwnership(run);List<SecurityReport> security=reports.findByValidationRunId(runId);String fingerprint=fingerprint(run,security);QualityGateResult existing=gates.findByValidationRunId(runId).stream().filter(x->policy.getPolicyVersion().equals(x.getPolicyVersion())&&fingerprint.equals(x.getEvidenceFingerprint())).findFirst().orElse(null);if(existing!=null)return existing;audit(run,EventType.QUALITY_GATE_EVALUATION_STARTED,null,null,"Quality gate evaluation started",null);
		List<QualityGateReason> reasons=new ArrayList<>();QualityGateDecision decision=QualityGateDecision.PASS;
		for(ValidationCheck c:run.getChecks()){if(c.isRequired()&&(c.getStatus()==ValidationStatus.FAILED||c.getStatus()==ValidationStatus.ERROR||c.getStatus()==ValidationStatus.BLOCKED)){reasons.add(reason("REQUIRED_CHECK_FAILED","ERROR",c.getName()+" did not pass","VALIDATION_CHECK",c.getCheckId(),true));decision=QualityGateDecision.BLOCK;}if(c.getType()==ValidationCheckType.SECURITY&&(c.getStatus()==ValidationStatus.FAILED||c.getStatus()==ValidationStatus.ERROR)){reasons.add(reason("SECURITY_SCANNER_FAILED","ERROR",c.getName()+" failed to execute","VALIDATION_CHECK",c.getCheckId(),true));decision=QualityGateDecision.BLOCK;}if(c.getType()==ValidationCheckType.SECURITY&&c.getStatus()==ValidationStatus.SKIPPED&&!"AVAILABLE".equals(c.getMetadata().get("availability"))){reasons.add(reason("SCANNER_UNAVAILABLE","WARNING",c.getName()+" is unavailable","VALIDATION_CHECK",c.getCheckId(),false));decision=max(decision,policy.getRequiredProviderUnavailable());}if(c.getType()==ValidationCheckType.BROWSER&&c.isRequired()&&c.getStatus()==ValidationStatus.SKIPPED&&!"AVAILABLE".equals(c.getMetadata().get("availability"))){reasons.add(reason("BROWSER_RUNTIME_UNAVAILABLE","WARNING",c.getName()+" is unavailable","VALIDATION_CHECK",c.getCheckId(),false));decision=max(decision,policy.getRequiredProviderUnavailable());}}
		EnumMap<SecuritySeverity,Integer> counts=new EnumMap<>(SecuritySeverity.class);for(SecuritySeverity s:SecuritySeverity.values())counts.put(s,0);for(SecurityReport report:security)for(SecurityFinding f:report.getFindings()){counts.merge(f.getSeverity(),1,Integer::sum);QualityGateDecision d=f.getCategory()==SecurityCategory.SECRET?policy.getSecret():policy.forSeverity(f.getSeverity());if(d!=QualityGateDecision.PASS||f.getSeverity()==SecuritySeverity.MEDIUM){String code=f.getCategory()==SecurityCategory.SECRET?"SECRET_DETECTED":f.getSeverity()+"_FINDING";reasons.add(reason(code,f.getSeverity().name(),f.getTitle(),"SECURITY_FINDING",f.getFindingId(),d==QualityGateDecision.BLOCK));}decision=max(decision,d);}
		QualityGateResult result=new QualityGateResult();result.setGateResultId("gate-"+UUID.randomUUID());result.setValidationRunId(runId);result.setTaskId(run.getTaskId());result.setProjectId(run.getProjectId());result.setWorkspaceId(run.getWorkspaceId());result.setChangeSetId(run.getChangeSetId());result.setExecutionWorkspaceId(run.getExecutionWorkspaceId());result.setValidatedChangeFingerprint(run.getValidatedChangeFingerprint());result.setPolicyVersion(policy.getPolicyVersion());result.setEvidenceFingerprint(fingerprint);result.setDecision(decision);result.setReasons(reasons);result.setCreatedAt(Instant.now());result.setDecidedAt(Instant.now());result.setValidationSummary(Map.of("status",run.getStatus().name(),"checks",run.getChecks().size()));Map<String,Object> summary=new LinkedHashMap<>();counts.forEach((k,v)->summary.put(k.name().toLowerCase(),v));result.setSecuritySummary(summary);
		if(decision==QualityGateDecision.REQUIRE_APPROVAL){HumanApproval approval=new HumanApproval("approval-"+UUID.randomUUID(),run.getTaskId(),runId,"quality-gate",result.getGateResultId(),HumanApprovalStatus.PENDING,"quality-gate",null,null,Instant.now(),null);approvals.save(approval);result.setApprovalId(approval.getApprovalId());}gates.save(result);audit(run,event(decision),result,null,"Quality gate "+decision,result.getApprovalId());return result;}
	public synchronized QualityGateResult approve(String gateId,String reviewer,String comment){QualityGateResult r=require(gateId);if(r.getDecision()==QualityGateDecision.PASS&&r.getStatus()==QualityGateStatus.APPROVED)return r;if(r.getDecision()!=QualityGateDecision.REQUIRE_APPROVAL)throw new IllegalStateException("Quality gate does not require approval");HumanApproval a=approvals.get(r.getApprovalId());if(a.getStatus()==HumanApprovalStatus.PENDING){a.approve(reviewer,comment);approvals.save(a);}r.setDecision(QualityGateDecision.PASS);r.setStatus(QualityGateStatus.APPROVED);r.setDecidedAt(Instant.now());gates.save(r);audit(validation(r),EventType.QUALITY_GATE_APPROVED,r,a.getApprovalId(),"Quality gate approved",a.getApprovalId());return r;}
	public synchronized QualityGateResult reject(String gateId,String reviewer,String comment){QualityGateResult r=require(gateId);if(r.getDecision()==QualityGateDecision.BLOCK&&r.getStatus()==QualityGateStatus.REJECTED)return r;if(r.getDecision()!=QualityGateDecision.REQUIRE_APPROVAL)throw new IllegalStateException("Quality gate does not require approval");HumanApproval a=approvals.get(r.getApprovalId());if(a.getStatus()==HumanApprovalStatus.PENDING){a.reject(reviewer,comment);approvals.save(a);}r.setDecision(QualityGateDecision.BLOCK);r.setStatus(QualityGateStatus.REJECTED);r.setDecidedAt(Instant.now());gates.save(r);audit(validation(r),EventType.QUALITY_GATE_REJECTED,r,a.getApprovalId(),"Quality gate rejected",a.getApprovalId());return r;}
	public void assertAllowed(String taskId){TaskRecord task=tasks.getTask(taskId).orElseThrow(()->new ResourceNotFoundException("Task",taskId));if(task.getExecutionMode()==ExecutionMode.READ_ONLY)throw new IllegalStateException("READ_ONLY task cannot perform Git write operations");ValidationRun run=validations.findByTaskId(taskId).stream().max(Comparator.comparing(ValidationRun::getStartedAt,Comparator.nullsFirst(Comparator.naturalOrder()))).orElseThrow(()->new IllegalStateException("Quality Gate denied: no ValidationRun for task"));QualityGateResult gate=gates.findByValidationRunId(run.getValidationRunId()).stream().filter(x->policy.getPolicyVersion().equals(x.getPolicyVersion())).max(Comparator.comparing(QualityGateResult::getCreatedAt)).orElseThrow(()->new IllegalStateException("Quality Gate denied: no gate result for latest ValidationRun"));if(gate.getDecision()!=QualityGateDecision.PASS)throw new IllegalStateException("Quality Gate denied: "+gate.getDecision()+" - "+gate.getReasons().stream().map(QualityGateReason::message).toList());}
	public QualityGateResult get(String id){return require(id);} public List<QualityGateResult> byValidation(String id){return gates.findByValidationRunId(id);}
	public void assertAllowedForChange(String taskId,String changeSetId){
		TaskRecord task=tasks.getTask(taskId).orElseThrow(()->new ResourceNotFoundException("Task",taskId));
		if(task.getExecutionMode()==ExecutionMode.READ_ONLY)throw new IllegalStateException("READ_ONLY task cannot perform Git write operations");
		ValidationRun run=validations.findByTaskId(taskId).stream().filter(v->changeSetId.equals(v.getChangeSetId())).max(Comparator.comparing(ValidationRun::getStartedAt,Comparator.nullsFirst(Comparator.naturalOrder()))).orElseThrow(()->new IllegalStateException("Quality Gate denied: no delivery ValidationRun for change"));
		QualityGateResult gate=gates.findByValidationRunId(run.getValidationRunId()).stream().filter(x->policy.getPolicyVersion().equals(x.getPolicyVersion())).max(Comparator.comparing(QualityGateResult::getCreatedAt)).orElseThrow(()->new IllegalStateException("Quality Gate denied: no gate result for change"));
		if(gate.getDecision()!=QualityGateDecision.PASS)throw new IllegalStateException("Quality Gate denied: "+gate.getDecision());
		if(run.isDelivery() && executionWorkspaces != null && run.getValidatedChangeFingerprint() != null){
			String current=executionWorkspaces.changeFingerprint(taskId);
			if(!run.getValidatedChangeFingerprint().equals(current)) throw new IllegalStateException("VALIDATION_STALE: execution workspace changed after validation");
		}
	}
	private QualityGateResult require(String id){QualityGateResult r=gates.get(id);if(r==null)throw new ResourceNotFoundException("QualityGateResult",id);return r;} private ValidationRun validation(QualityGateResult r){return validations.get(r.getValidationRunId());}
	private void requireOwnership(ValidationRun r){TaskRecord t=tasks.getTask(r.getTaskId()).orElseThrow(()->new ResourceNotFoundException("Task",r.getTaskId()));if(!java.util.Objects.equals(t.getProjectId(),r.getProjectId())||(!r.isDelivery()&&!java.util.Objects.equals(t.getWorkspaceId(),r.getWorkspaceId())))throw new IllegalArgumentException("Validation ownership mismatch");}
	private QualityGateReason reason(String c,String s,String m,String st,String id,boolean b){return new QualityGateReason(c,s,m==null?c:m,st,id,b);} private QualityGateDecision max(QualityGateDecision a,QualityGateDecision b){if(a==QualityGateDecision.BLOCK||b==QualityGateDecision.BLOCK)return QualityGateDecision.BLOCK;if(a==QualityGateDecision.REQUIRE_APPROVAL||b==QualityGateDecision.REQUIRE_APPROVAL)return QualityGateDecision.REQUIRE_APPROVAL;return QualityGateDecision.PASS;}
	private EventType event(QualityGateDecision d){return switch(d){case PASS->EventType.QUALITY_GATE_PASSED;case BLOCK->EventType.QUALITY_GATE_BLOCKED;case REQUIRE_APPROVAL->EventType.QUALITY_GATE_APPROVAL_REQUIRED;};}
	private void audit(ValidationRun run,EventType type,QualityGateResult gate,String ignored,String summary,String approvalId){Map<String,Object> m=new LinkedHashMap<>();m.put("validationRunId",run.getValidationRunId());if(gate!=null)m.put("gateResultId",gate.getGateResultId());if(approvalId!=null)m.put("approvalId",approvalId);audit.qualityGateEvent(type,run.getTaskId(),run.getValidationRunId(),gate==null?null:gate.getGateResultId(),approvalId,summary,m);}
	private String fingerprint(ValidationRun r,List<SecurityReport> s){try{List<SecurityReport> ordered=s.stream().sorted(Comparator.comparing(SecurityReport::getReportId)).toList();return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(mapper.writeValueAsString(List.of(r,ordered)).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
