package com.aidevos.orchestrator.optimization;

import java.time.Instant;

/**
 * One autonomous optimization record: a recommendation produced for a task
 * or runtime session, its category, confidence and the time it was created.
 * Records are generated by OptimizationService and stored in the in-memory
 * optimization repository (no database migration); they are never applied
 * automatically.
 */
public class OptimizationRecord {

	private final String id;
	private final String taskId;
	private final String sessionId;
	private final OptimizationType type;
	private final String recommendation;
	private final double confidence;
	private final Instant createdAt;

	public OptimizationRecord(String id, String taskId, String sessionId,
			OptimizationType type, String recommendation, double confidence,
			Instant createdAt) {
		this.id = id == null || id.isBlank() ? "optimization-" + System.nanoTime() : id;
		this.taskId = taskId;
		this.sessionId = sessionId;
		this.type = type == null ? OptimizationType.PERFORMANCE : type;
		this.recommendation = recommendation == null ? "" : recommendation;
		this.confidence = confidence;
		this.createdAt = createdAt == null ? Instant.now() : createdAt;
	}

	public String getId() {
		return id;
	}

	public String getTaskId() {
		return taskId;
	}

	public String getSessionId() {
		return sessionId;
	}

	public OptimizationType getType() {
		return type;
	}

	public String getRecommendation() {
		return recommendation;
	}

	public double getConfidence() {
		return confidence;
	}

	public Instant getCreatedAt() {
		return createdAt;
	}
}
